### PR TITLE
Update VertexAI instructions to match new UI

### LINKED ISSUE #265: https://docs.rapids.ai/deployment/nightly/cloud/gcp/vertex-ai/

### PR DESCRIPTION
**Pull request by betatim**
Closes #265 

This updates the instructions for Vertex AI to match the new UI. The downside of this is that when you start the notebook loading the additional kernel takes "the age of the universe". I stopped waiting after maybe 10min or so.

This means this is kind of a solution, but also not really.

It seems like this method of using your own docker image (or using it in addition) is becoming deprecated. At least that is the feeling I get from how hidden the options are for selecting it.

---

I've tried installing rapids via conda or cudf via pip in a "bog standard" Vertex AI notebook environment. This kinda works. The conda install takes a long time to solve and then fails at the end with a permission error (`[Errno 13] Permission denied: '/opt/conda/lib/python3.10/site-packages/google/protobuf/__pycache__/__init__.cpython-310.pyc`). The `pip` route is much quicker, it also fails with a permission error.

`nvidia-smi` output:
```
Tue Aug  8 07:56:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    29W / 250W |      0MiB / 16384MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Thanks @betatim. Would you mind adding a little info to the "Test RAPIDS" section about what the user should expect to see after they open Jupyter Lab?

If I remember right it shows the standard kernels and a little toast popup appears saying it is importing the RAPIDS kernel, then after some amount of time (~20 mins) the RAPIDS kernel should appear as an option.

Maybe put this in a warning box?

**Comment by jacobtomlinson** [comment]
cc @taureandyernv for Vertex AI `nvidia-smi` output.

**Comment by betatim** [comment]
> Thanks @betatim. Would you mind adding a little info to the "Test RAPIDS" section about what the user should expect to see after they open Jupyter Lab?
> 
> If I remember right it shows the standard kernels and a little toast popup appears saying it is importing the RAPIDS kernel, then after some amount of time (~20 mins) the RAPIDS kernel should appear as an option.

That is how I remember it as well. Just started a new session to see how long it really takes and it has now been 35min and all I see is the "Loading kernel ..." message :-/

**Comment by jacobtomlinson** [comment]
Ouch that's a long time.

**Pull request merged**
