### PR TITLE
Basic outline and draft content for AWS

### PR DESCRIPTION
**Pull request by mmccarty**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
@mmccarty I've refactored this to align with the structure I merged in #19

**Comment by jacobtomlinson** [comment]
@hcho3 as you have been testing the AWS Cloud example notebooks would you mind also reviewing this PR and ensuring the examples work? I expect there will be a lot of overlap.

**Comment by hcho3** [comment]
@jacobtomlinson Yes, I'm happy to review it.

**Comment by taureandyernv** [comment]
do we want to include SageMaker Studio Lab in this or SageMaker Studio?

**Comment by jacobtomlinson** [comment]
@taureandyernv yeah definitely, we are tracking that in #13 which is targeted for 22.10.

**Comment by mmccarty** [comment]
@jacobtomlinson Should we just merge or close this PR?

**Review by hcho3 — APPROVED** [review]

**Pull request merged**
