### PR TITLE
start using CUDA 12.5, Python 3.11 images in nightly docs

### PR DESCRIPTION
**Pull request by jameslamb**
Contributes to #377.

Proposes using CUDA 12.5, Python 3.11 container images for the nightly docs. This should make it easier to test with these versions during release testing for 24.08. And hopefully that testing goes well and we can move on to setting the stable versions to these images as well.

CUDA 12.5 `rapidsai/base` and `rapidsai/notebooks` images were added in https://github.com/rapidsai/docker/pull/689, as part of https://github.com/rapidsai/build-planning/issues/73.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks James! 🙏

Seems like a good idea 👍

Let's see what @jacobtomlinson thinks 🙂

**Review by jacobtomlinson — COMMENTED** [review]
This seems like a good change.

I just want to double check my understanding about backward compatibility. If a platform gives us nodes with CUDA 12.0, are we fine to use the CUDA 12.5 images? My understanding is that there is backward compatibility within major versions these days, but I just want to check that is true.

**Comment by jakirkham** [comment]
Yes that is still how things work

As long as they supply hardware that supports CUDA 12 and there is a driver that supports CUDA 12 (either provided by them or us via a container), then it should work

Please see [this page for driver versions]( https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-11-and-later-defaults-to-minor-version-compatibility )

**Comment by jacobtomlinson** [comment]
Thanks @jakirkham that's really helpful!

**Comment by jakirkham** [comment]
Thanks Jacob and James! 🙏

**Pull request merged**
